import type { Metadata } from "next";
import { Be_Vietnam_Pro as BeVietnamPro } from "next/font/google";
import "./globals.css";

const beVietnamPro = BeVietnamPro({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beVietnamPro.className}>{children}</body>
    </html>
  );
}
